openapi: 3.0.3

paths:
  /auth/sign-in:
    post:
      tags:
        - Auth
      summary: Sign in
      description: Authenticate user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInDto"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInResponse"
        "401":
          description: Unauthorized - Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                statusCode: 401
                message: Wrong account
                error: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SignInDto:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User email address
        password:
          type: string
          format: password
          description: User password

    SignInResponse:
      type: object
      properties:
        iat:
          type: number
          description: Token issued at (Unix timestamp)
        exp:
          type: number
          description: Token expiration time (Unix timestamp)
        sub:
          type: number
          description: User ID
        access_token:
          type: string
          description: JWT access token
        refresh_token:
          type: string
          description: JWT refresh token

    Error:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
        error:
          type: string

