openapi: 3.0.3

paths:
  /projects:
    post:
      tags:
        - Projects
      summary: Create a new project
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectDto"
      responses:
        "201":
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"

    get:
      tags:
        - Projects
      summary: Get all projects
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: description
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/ProjectStatus"
        - name: owner_id
          in: query
          schema:
            type: string
        - name: member_id
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ProjectResponse"
                  total:
                    type: number
                  page:
                    type: number
                  limit:
                    type: number
                  total_pages:
                    type: number

  /projects/member-of:
    get:
      tags:
        - Projects
      summary: Get projects I am a member of
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectMemberOfResponse"

  /projects/{id}:
    get:
      tags:
        - Projects
      summary: Get project by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Project details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectResponse"
        "404":
          $ref: "#/components/responses/NotFound"

    patch:
      tags:
        - Projects
      summary: Update project
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProjectDto"
      responses:
        "200":
          description: Project updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      tags:
        - Projects
      summary: Delete project
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Project deleted successfully
        "404":
          $ref: "#/components/responses/NotFound"

  /projects/{id}/stats:
    get:
      tags:
        - Projects
      summary: Get project statistics
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Project statistics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectStatsResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateProjectDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 3000
        tags:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date

    UpdateProjectDto:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 3000
        tags:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE, COMPLETED, CANCELLED]
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date

    ProjectResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE, COMPLETED, CANCELLED]
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        owner:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
            first_name:
              type: string
            last_name:
              type: string
            fullName:
              type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        member_count:
          type: number
        invite_count:
          type: number

    ProjectStatsResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        member_count:
          type: number
        invite_count:
          type: number
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time

    ProjectMemberOfResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProjectResponse"
