export enum USER_ROLE {
  ADMIN = 'ADMIN', // system admin
  PM = 'PROJECT_MANAGER', // project manager
  DEVELOPER = 'DEVELOPER', // developer
  QA = 'QUALITY_ASSURANCE', // quality assurance
  QC = 'QUALITY_CONTROL', // tester
  BR_COMT = 'BRSE_COMTOR', // Bridge Software Engineer
}

export enum PROJECT_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MEMBER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  LEFT = 'LEFT',
}

export enum PROJECT_ROLE {
  PROJECT_MANAGER = 'PROJECT_MANAGER', // project manager
  DEVELOPER = 'DEVELOPER', // developer
  QA = 'QUALITY_ASSURANCE', // quality assurance
  QC = 'QUALITY_CONTROL', // tester
  BRSE_COMTOR = 'BRSE_COMTOR', // Bridge Software Engineer
}

export enum INVITE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum TASK_TYPE {
  TASK = 'TASK',
  CHANGE_REQUEST = 'CHANGE_REQUEST',
  FEEDBACK = 'FEEDBACK',
  NEW_FEATURE = 'NEW_FEATURE',
  SUB_TASK = 'SUB_TASK',
  IMPROVEMENT = 'IMPROVEMENT',
  BUG = 'BUG',
  BUG_CUSTOMER = 'BUG_CUSTOMER',
  LEAKAGE = 'LEAKAGE',
}

export enum TASK_STATUS {
  OPEN = 'OPEN',
  REOPEN = 'REOPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  DONE = 'DONE',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
}

export enum TASK_PRIORITY {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum SPRINT_STATUS {
  PLANNING = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  CLOSED = 'CLOSED',
}

export enum GIT_ALERT_TYPE {
  MERGED = 'MERGED',
  BUILD = 'BUILD',
  TEST = 'TEST',
  CONFLICT = 'CONFLICT',
  COMMENT = 'COMMENT',
  PULL_REQUEST = 'PULL_REQUEST',
  PUSH = 'PUSH',
  PIPELINE = 'PIPELINE',
}

export enum GIT_ALERT_PRIORITY {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum GIT_REPOSITORY_PROVIDER {
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
}

export enum GIT_ALERT_TAG {
  NEW = 'NEW',
  NEED_HANDLING = 'NEED_HANDLING',
  PIPELINE_FAILED = 'PIPELINE_FAILED',
  PIPELINE_SUCCESS = 'PIPELINE_SUCCESS',
  PIPELINE_IN_PROGRESS = 'PIPELINE_IN_PROGRESS',
}
