export enum FILE_KIND {
  DOCUMENT = 'DOCUMENT',
  VIDEO = 'VIDEO',
  IMAGE = 'IMAGE',
  ARCHIVE = 'ARCHIVE',
  AUDIO = 'AUDIO',
  OTHER = 'OTHER',
}

export enum STORAGE_DRIVER {
  LOCAL = 'LOCAL',
  CLOUDINARY = 'CLOUDINARY',
}

export enum STORAGE_DELETE_MODE {
  SOFT = 'SOFT',
  HARD = 'HARD',
}
