# docker-compose.yml

services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - pm-tools-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - pm-tools-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - pm-tools-network

volumes:
  postgres:

networks:
  pm-tools-network:
    driver: bridge
